### ISSUE TITLE
home assistant database

### ISSUE THREAD

**Issue by cc120689** [fuslwusl/homeassistant-addon-victoriametrics#10]
Hello, first of all thank you for your work.
I have installed your addon and it works very well in grafana, but grafana not so much on home assistant, especially when you connect successively from outside and from within your own network.
I wanted to know if there is any way for the home assistant to read the sensors directly from the victoria metrics database, thanks again, best regards.

**Comment by fuslwusl** [comment]
It seems to be possible using an [influxdb sensor ](https://community.home-assistant.io/t/import-influxdb-data-as-sensor-in-home-assistant/216722) 
Victoria Metrics is 100 percent compatible with influxdb.

**Comment by cc120689** [comment]
Ok thanks!i will try it

**Comment by guirem** [comment]
Hi @fuslwusl,
Do you mean victoriametrics is compatible with InfluxQL (used by influxdb sensor)?
