### ISSUE TITLE
Use vmagent instead of full victoria metrics

### ISSUE THREAD

**Issue by lapo-luchini** [fuslwusl/homeassistant-addon-victoriametrics#25]
For those of us that already have an existing Victoria Metrics in the home network, but would prefer to use the local caching provided by `vmagent` (so that no data is ever lost, even if/when the external Victoria Metrics is unreachable), I [created a fork of this project](https://github.com/lapo-luchini/homeassistant-addon-vmagent) that does just that.

**Comment by fuslwusl** [comment]
This addon was meant to be a easy replacement for the influxdb addon. If you have some sort of special cases you can just fork an use your modified version.
