### ISSUE TITLE
Better instruction for configuring InfluxDB interface

### ISSUE THREAD

**Issue by asoltesz** [fuslwusl/homeassistant-addon-victoriametrics#27]
The README.md doesn't include detailed instructions on how to configure InfluxDB for the newly installed VictoriaMetrics addon.

This is a problem for less experienced Home Assistant and InfluxDB users (like me).

Detailed instructions would allow the effective installation/configuration of this plugin. 

As it is, people may just get stuck at configuring InfluxDB for VM and finally give up on the whole thing and remove the VictoriaMetrics addon.

It would also be important to explain how to validate the setup so that people can be sure that data is collected properly and can be queried as well (e.g.: via Grafana)

**Comment by fuslwusl** [comment]
Hi, is this doc not enough?
https://github.com/fuslwusl/homeassistant-addon-victoriametrics/blob/main/victoria-metrics/DOCS.md

I tried my best to explain the right configuration and usage.
Better docs are welcome as pullrequests.

**Comment by asoltesz** [comment]
Yes, that documentation is good enough and using it is how I finally solved the issue and made VM working in my Home Assistant instance.

However, I missed it for the first couple of attempts and only noticed it much later (due to being  beginner and not used to the "Documentation" tab of addons). I tried to make it work only via the README.md and didn't notice the content of the Documentation tab at all.

I would recommend linking the DOCS.md into the README.md of the repo as well so that everybody finds it easily.

In the "Installation and configuration" section, under point 3, I would write something like this:

~~~
Configure VictoriaMetrics using its [addon configuration documentation](DOCS.md) which can also be found on the Documentation tab of the addon in the Home Assistant settings.
~~~

instead of the current text:
~~~
Read the add-on documentation in the Victoria Metrics documentation tab
~~~

I can propose the change with a PR if you think it makes things better.

**Comment by fuslwusl** [comment]
Thanx for your feedback. README.md updated.

**Comment by mikeyroy** [comment]
I would add it would be useful to be a little more specific with these influxdb config options:
```
  host: <<<ADD-ON HOSTNAME FROM VICTORIA METRICS ADD-ON PAGE>>>
  port: 8428 # Victoria Metrics port
```

Then because it is stated `Add influxdb integration to your homeassistant config` it implies that the influxdb documentation should be completed which includes creating a db and users, it would be helpful to state:
`Add influxdb integration to your homeassistant config - only complete the Installation step and make sure the integration starts`

Thanks for your work on this!
