### ISSUE TITLE
victoriametrics disk usage

### ISSUE THREAD

**Issue by wavoigt** [fuslwusl/homeassistant-addon-victoriametrics#28]
Hi,
If i do a backup of HA with Victoriametrics, it has a compressed size of > 50MB.
Without Victoriametrics the size is 10MB.
This sounds not to be so much, but  if i i do the backup it takes 5 times longer.
I saw that Victoria metrics brings along many libraries whitch have an uncompressed size of 120Mb.
Is it possible to shrink the Add-On e.g. without all the libraries? I don't want to build it by myself.
Regards, Walter

**Comment by fuslwusl** [comment]
I don't know any way to reduce the size for this addon. If anybody knows a way just tell me and i will try it out.
