### ISSUE TITLE
How to rewrite labels

### ISSUE THREAD

**Issue by andyfr** [fuslwusl/homeassistant-addon-victoriametrics#31]
Hi,

I want to change some labels and the name of metrics. I followed the VictoriaDB guide and setup a relabel config. Now I'm struggling with where to place the relabel config.

Does this work at all, when using the influx integration?

For completeness, I want to apply following config:
- source_labels: [__name__]
  regex: 'sensor..*_plant_sensor_(.*)_value'                       
  replacement: '$1'
  target_label: plant_id
- source_labels: [__name__]
  regex: 'sensor.(.*)_plant_sensor_.*_value'                       
  replacement: '$1'
  target_label: sensor_type
- source_labels: [__name__]
  regex: 'sensor..*_plant_sensor_.*_value'                       
  replacement: sensor.plant_sensor
  target_label: __name__

**Comment by andyfr** [comment]
It took me a while to figure out it need to add it to the scrape configuration in [prometheus.tpl](https://github.com/fuslwusl/homeassistant-addon-victoriametrics/blob/main/victoria-metrics/prometheus.tpl). (Never used victoriadb/prometheus before)

Is there a recommended way to replace the configuration?
As far as I can see, this might be related to [Map the Home Assistant config directory to the add-on container](https://github.com/fuslwusl/homeassistant-addon-victoriametrics/issues/29), although I don't care about the location of the configuration file, as long as I can change it ;)

**Comment by denisgolius** [comment]
> It took me a while to figure out it need to add it to the scrape configuration in [prometheus.tpl](https://github.com/fuslwusl/homeassistant-addon-victoriametrics/blob/main/victoria-metrics/prometheus.tpl). (Never used victoriadb/prometheus before)
> 
> Is there a recommended way to replace the configuration? As far as I can see, this might be related to [Map the Home Assistant config directory to the add-on container](https://github.com/fuslwusl/homeassistant-addon-victoriametrics/issues/29), although I don't care about the location of the configuration file, as long as I can change it ;)

Hey @andyfr, 
we have a great [coockbook](https://docs.victoriametrics.com/relabeling.html) about relabeling. You can do some opactice at

**Comment by fuslwusl** [comment]
@denisgolius Thanx for your help!
