### ISSUE TITLE
SSL configs

### ISSUE THREAD

**Issue by danielnolan** [fuslwusl/homeassistant-addon-victoriametrics#36]
Is there a way to configure this addon to use Home Assistants SSL certificates like you can for other addons?

**Comment by danielnolan** [comment]
I was able to get this to work by copying the home assistant ssl directory to the home assistant share directory, and using the victoria addon additional arguments config like this `-tls -tlsCertFile=/share/ssl/fullchain.pem -tlsKeyFile=/share/ssl/privkey.pem`
Is there anyway the ssl directory can be added to the container so I don't have to copy the ssl certs in two directories?

**Comment by fuslwusl** [comment]
@danielnolan Check out the latest release 1.9.0 - the ssl path is added to the container.

**Comment by danielnolan** [comment]
Works great, thank you!
