### ISSUE TITLE
[feature] Add support for graphite

### ISSUE THREAD

**Issue by googanhiem** [fuslwusl/homeassistant-addon-victoriametrics#37]
I'd like to enable graphite listening server, as documented [here](https://docs.victoriametrics.com/url-examples/?highlight=graphite#how-to-send-graphite-data-to-victoriametrics)

I can add the argument `-graphiteListenAddr=8867` , but get an error.  It returns `error fatal	VictoriaMetrics/lib/ingestserver/graphite/server.go:48	cannot start TCP Graphite server at "8867": listen tcp4: address 8867: missing port in address`

If you could add the ability to specify another port I imagine that would solve the issue.

**Comment by denisgolius** [comment]
> I'd like to enable graphite listening server, as documented [here](https://docs.victoriametrics.com/url-examples/?highlight=graphite#how-to-send-graphite-data-to-victoriametrics)
> 
> I can add the argument `-graphiteListenAddr=8867` , but get an error. It returns `error fatal VictoriaMetrics/lib/ingestserver/graphite/server.go:48 cannot start TCP Graphite server at "8867": listen tcp4: address 8867: missing port in address`
> 
> If you could add the ability to specify another port I imagine that would solve the issue.

Hey @googanhiem , try once again but put `:` symbol before port number, for example:
```shell
-graphiteListenAddr=:8867
```

**Comment by googanhiem** [comment]
Yes, adding that allowed it to launch.  Thanks

I'm trying to get Truenas Scale to export to it. As its a separate machine I think the port is being blocked by HAOS.

**Comment by fuslwusl** [comment]
Thanx for your feedback!
