### ISSUE TITLE
Question: migrate this repository to https://github.com/orgs/VictoriaMetrics-Community organization

### ISSUE THREAD

**Issue by denisgolius** [fuslwusl/homeassistant-addon-victoriametrics#46]
Would you mind to migrate this repository to https://github.com/orgs/VictoriaMetrics-Community organization and continue to update and support it there?

PS:  I created a  https://github.com/VictoriaMetrics-Community/homeassistant-addon-victorialogs . Would be great if you will take a look on it and give some feedback if there any 😉

**Comment by fuslwusl** [comment]
@denisgolius Just contact me to discuss options.

**Comment by denisgolius** [comment]
Ok, but how to do it? You don't have any contact information in your GitHub profile.
